apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ms
  template:
    metadata:
      labels:
        app: postgres-ms
    spec:
      containers:
        - name: postgres-ms
          image: postgres:15
          args:
            - "-c"
            - "max_connections=5000"
          env:
            - name: POSTGRES_DB
              value: db-ms
            - name: POSTGRES_USER
              value: postgres-ms
            - name: POSTGRES_PASSWORD
              value: masterkey
          ports:
            - containerPort: 5432
